MVC2/Models/Companies/CityModel.cs
namespace MVC2.Models.Companies
{
    public class CityModel
    {
        public int CityId { get; set; }

        public string CityName { get; set; }
    }
}

MVC2/Models/Companies/CompanyContact.cs
namespace MVC2.Models.Companies
{
    public class CompanyContact
    {
        public int ContactId { get; set; }

        public string ContactName { get; set; }

        public string Telephone { get; set; }
    }
}

MVC2/Models/Companies/CompanyModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace MVC2.Models.Companies
{
    public class CompanyModel
    {
        public int CompanyId { get; set; }

        [MinLength(3, ErrorMessage = "The length must be more than 3")]
        [DisplayName("Company name")]
        [Required(ErrorMessage = "Company name is required")]
        public string CompanyName { get; set; }

        [DisplayName("City")]
        public List<CityModel> Cities { get; set; }

        //public List<CompanyContact> CompanyContacts;

        public int SelectedCityId { get; set; }

        [DisplayName("City")]
        public string SelectedCityName { get; set; }

        //public List<string> GetContactsWithPhones()
        //{
        //    return CompanyContacts.Select(x => x.ContactName + " " + x.Telephone).ToList();
        //}
    }
}

MVC2/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Cryptography.X509Certificates;
using System.Web.Mvc;
using Airport.Core.Interfaces.Managers;
using MVC2.Models.Companies;

namespace MVC2.Controllers
{
	public class CompaniesController : Controller
	{

		public CompaniesController()
		{

		}
		private readonly ICompanyManager _companyManager;
		//private readonly ICityManager _cityManager;
		private readonly List<CityModel> _cities;

		public CompaniesController(ICompanyManager companyManager, ICityManager cityManager)
		{
			_companyManager = companyManager;
			//_cityManager = cityManager;

			_cities = cityManager.GetAllCities().Select(x => new CityModel()
			{
				CityId = x.CityId,
				CityName = x.CityName
			}).ToList();

			//_cities = new List<CityModel>(new[]     // TODO: get cities from _cityRepository
			//{
			//    new CityModel
			//    {
			//        CityId = 1,
			//        CityName = "Kiev"
			//    },
			//    new CityModel
			//    {
			//        CityId = 2,
			//        CityName = "Odessa"
			//    }
			//});
		}

		// GET: Companies
		//[OutputCache(Duration = 300)] // 5 minutes
		public ActionResult Index()
		{
			ViewBag.RoleAdmin = User.IsInRole("Admin");
			var companies = _companyManager.GetAllCompanies();
			return View(companies);
		}

		[Authorize(Roles = "Admin")]
		public ActionResult AddNewCompany()
		{
			var model = new CompanyModel
			{
				Cities = _cities
			};

			return View("CompanyDetails", model);
		}

		[ValidateAntiForgeryToken]
		[HttpPost]
		[Authorize(Roles = "Admin")]
		public ActionResult AddNewCompany(CompanyModel company)
		{
			// unique CompanyName
			if (!string.IsNullOrEmpty(company.CompanyName))
			{
				var record = _companyManager.GetAllCompanies()
											.FirstOrDefault(x => string.Equals(x.CompanyName, company.CompanyName, StringComparison.InvariantCultureIgnoreCase));
				company.Cities = _cities;
				if (record != null) ModelState.AddModelError(nameof(company.CompanyName), $"We already have company '{company.CompanyName}' in DB");
			}

			if (ModelState.IsValid)
			{
				_companyManager.AddCompany(company.CompanyName, company.SelectedCityId);
				return RedirectToAction("Index");
			}

			return View("CompanyDetails", company);
		}

		[Authorize(Roles = "Admin")]
		public ActionResult EditCompany(int companyId)
		{
			var model = GetModel(companyId);
			return View("CompanyDetails", model);
		}

		[ValidateAntiForgeryToken]
		[HttpPost]
		[Authorize(Roles = "Admin")]
		public ActionResult EditCompany(CompanyModel company)
		{
			if (!string.IsNullOrEmpty(company.CompanyName))
			{
				var oldCompany = _companyManager.GetCompanyById(company.CompanyId);
				if (!oldCompany.CompanyName.Equals(company.CompanyName, StringComparison.InvariantCultureIgnoreCase))
				{
					var record = _companyManager.GetAllCompanies()
						.FirstOrDefault(x => string.Equals(x.CompanyName, company.CompanyName, StringComparison.InvariantCultureIgnoreCase));
					company.Cities = _cities;
					if (record != null) ModelState.AddModelError(nameof(company.CompanyName), $"We already have company '{company.CompanyName}' in DB");
				}
			}
			if (ModelState.IsValid)
			{
				_companyManager.EditCompany(company.CompanyId, company.CompanyName, company.SelectedCityId);
				return RedirectToAction("Index");
			}

			return View("CompanyDetails", company);
		}

		public ActionResult CompanyPreview(int companyid)
		{
			var model = GetModel(companyid);
			return PartialView(model);
		}

		private CompanyModel GetModel(int companyId)
		{
			var company = _companyManager.GetCompanyById(companyId);
			var model = new CompanyModel
			{
				CompanyId = company.CompanyId,
				CompanyName = company.CompanyName,
				Cities = _cities,
				SelectedCityId = company.CityId,
				SelectedCityName = _cities.FirstOrDefault(x => x.CityId == company.CityId)?.CityName ?? ""
			};

			return model;
		}
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteCompany(int companyId)
        {
            try
            {

                var model = GetModel(companyId);
                return View(model);
            }

            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteCompany(CompanyModel company)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _companyManager.DeleteCompany(company.CompanyId);
                    return RedirectToAction("Index");
                }
                else
                {
                    return HttpNotFound();
                }

            }

            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }
    }
}

MVC2/Views/Companies/CompanyDetails.cshtml
@model  MVC2.Models.Companies.CompanyModel

@{
    var action = Model.CompanyId > 0 ? "EditCompany" : "AddNewCompany";
    var header = Model.CompanyId > 0 ? "Edit company" : "Add new company";
    var buttonText = Model.CompanyId > 0 ? "Save" : "Create";
}

<div class="container body-content" style="margin-top: 20px;">
    @using (Html.BeginForm(action, "Companies", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>@header</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(x => x.CompanyId)

            <div class="form-group">
                @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Cities, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <select name="SelectedCityId" id="SelectedCityId" class="form-control" placeholder="Select city">
                        @foreach (var itm in Model.Cities)
                        {
                            if (Model.SelectedCityId == itm.CityId)
                            {
                                <option name="Cities" value="@itm.CityId" selected>@itm.CityName</option>
                            }
                            else
                            {
                                <option name="Cities" value="@itm.CityId">@itm.CityName</option>
                            }
                        }
                    </select>

                    @*@Html.DropDownListFor(n => n.Cities, new SelectList(Model.Cities), "Please select city", new { htmlAttributes = new { @class = "form-control" } })*@
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="@buttonText" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

MVC2/Views/Companies/CompanyPreview.cshtml
@model MVC2.Models.Companies.CompanyModel

<div data-companyid="@Model.CompanyId" class="company-preview">
    <div class="form-group row">
        @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-8">
            @Html.DisplayFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(model => model.SelectedCityName, htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-8">
            @Html.DisplayFor(model => model.SelectedCityName, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
</div>

MVC2/Views/Companies/DeleteCompany.cshtml
@model MVC2.Models.Companies.CompanyModel

@{
    ViewBag.Title = "Company Delete";
}


<h3>Are you sure you want to delete this company?</h3>

<div class="container body-content" style="margin-top: 20px;">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(x => x.CompanyName)

            <div class="form-group">

                @Html.DisplayNameFor(model => model.CompanyName)

                @Html.DisplayFor(model => model.CompanyName)
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </div>
            </div>


        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

MVC2/Views/Companies/Index.cshtml
@model Airport.Core.Models.Company[]

@{
    ViewBag.Title = "Companies";
    var RoleAdmin = ViewBag.RoleAdmin;
}
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Company Table</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="company" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>CompanyId</th>
                                <th>CompanyName</th>
                                <th>CityName</th>
                                @if (RoleAdmin)
                                {
                                    <th>Actions</th>
                                }
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var itm in Model)
                            {
                            <tr id="companyId-@itm.CompanyId">
                                <td>@itm.CompanyId</td>
                                <td>@itm.CompanyName</td>
                                <td>@itm.City.CityName</td>
                                @if (RoleAdmin)
                                {
                                    <td>
                                        @Html.ActionLink("Edit", "EditCompany", new { CompanyId = itm.CompanyId }, new { @class = "btn btn-primary btn-success btn-xs" })
                                        @Html.ActionLink("Delete", "DeleteCompany", new { CompanyId = itm.CompanyId }, new { @class = "btn btn-primary btn-danger btn-xs" })
                                    </td>
                                }
                            </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>CompanyId</th>
                                <th>CompanyName</th>
                                <th>CityName</th>
                                @if (RoleAdmin)
                                {
                                    <th>Actions</th>
                                }
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            @if (RoleAdmin)
            {
                @Html.ActionLink("Add new Company", "AddNewCompany", routeValues: null, htmlAttributes: new { id = "AddLink", @class = "btn bg-orange btn-flat margin" })
            }
        </div>
    </div>
</section>
@section Scripts{
    <script>
        $(function () {
            $('#company').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': false,
                'ordering': true,
                'info': true,
                'autoWidth': false
            })
        })
    </script>
}

@*@{
    ViewBag.Title = "Companies";
    var RoleAdmin = ViewBag.RoleAdmin;

    var ajaxOptions = new AjaxOptions
    {
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "companyDetails",
        OnSuccess = "previewSuccess",
        OnFailure = "previewFailure",
        OnBegin = "showLoader",
        OnComplete = "closeLoader"
    };
}

@section Styles{
    <style type="text/css">
        table {
            width: 100%;
        }

        table, th, td {
            border: 1px solid black;
            padding: 10px;
        }

            table thead th {
                background-color: green;
                color: white;
            }

            table tbody tr.selected {
                background-color: pink;
            }
    </style>
}



<div class="container">
    <div class="row">
        <div class="col-md-7">
            <table>
                <thead>
                    <tr>
                        <th>CompanyId</th>
                        <th>CompanyName</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var itm in Model)
                    {
                        <tr id="companyId-@itm.CompanyId">
                            <td>@itm.CompanyId</td>
                            <td>@itm.CompanyName</td>
                            <td>
                                @if (RoleAdmin)
                                {
                                    <span>@Html.ActionLink("Edit", "EditCompany", new { companyId = itm.CompanyId })</span>
                                }
                                <span style="margin-left: 5px;">@Ajax.ActionLink("Details", "CompanyPreview", new { companyId = itm.CompanyId }, ajaxOptions, null)</span>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            @if (RoleAdmin)
            {
                <div style="margin-top: 20px; margin-left: 10px; margin-bottom: 20px;">
                    @Html.ActionLink("Add new company", "AddNewCompany")
                </div>
            }
        </div>

        <div class="col-md-5" id="companyDetails" style="border: solid 1px black; padding: 10px;">
            <h2>Company details will be here</h2>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        function previewSuccess() {
            var elem = $("#companyDetails").find(".company-preview");
            if (elem) {
                var id = $(elem).data("companyid");

                //$("table tbody tr").css({ "background-color": "white" });               // skip color for all rows
                //$("table tbody tr#companyId-" + id).css({ "background-color": "yellow" });  // colorize current

                $("table tbody tr").removeClass("selected");
                $("table tbody tr#companyId-" + id).addClass("selected");
            }
        }

        function previewFailure() {
            console.log("Update preview failure");
        }

        function showLoader() {
            // TODO: display img with spinner
        }

        function closeLoader() {
            // TODO: hide img with spinner
        }
    </script>
}*@