MVC2/Models/Terminals/TerminalModel.cs
namespace MVC2.Models.Terminals
{
    public class TerminalModel
    {
        public int TerminalId { get; set; }

        public string TerminalName { get; set; }
    }
}

MVC2/Controllers/TerminalController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Airport.Core.Interfaces.Managers;
using MVC2.Models.Terminals;

namespace MVC2.Controllers
{
	public class TerminalController : Controller
    {
	    public TerminalController()
	    {
		    
	    }
	    private readonly ITerminalManager _terminalManager;

	    public TerminalController(ITerminalManager terminalManager)
	    {
			_terminalManager = terminalManager;
		    
		}
		// GET: terminals
		public ActionResult Index()
        {
	        ViewBag.RoleAdmin = User.IsInRole("Admin");
			var terminals = _terminalManager.GetAllTerminals();
	        return View(terminals);
        }
	    [Authorize(Roles = "Admin")]
		public ActionResult AddNewTerminal()
		{
			var model = new TerminalModel();

			return View("TerminalDetails", model);
		}

		[ValidateAntiForgeryToken]
		[HttpPost]
		[Authorize(Roles = "Admin")]
		public ActionResult AddNewTerminal(TerminalModel terminal)
		{
			if (!string.IsNullOrEmpty(terminal.TerminalName))
			{
				var record = _terminalManager.GetAllTerminals()
					.FirstOrDefault(x => string.Equals(x.TerminalName, terminal.TerminalName, StringComparison.InvariantCultureIgnoreCase));
				if (record != null) ModelState.AddModelError(nameof(terminal.TerminalName), $"We already have terminal '{terminal.TerminalName}' in DB");
			}

			if (ModelState.IsValid)
			{
				_terminalManager.AddTerminal(terminal.TerminalName);
				return RedirectToAction("Index");
			}

			return View("TerminalDetails", terminal);
		}
	    [Authorize(Roles = "Admin")]
		public ActionResult EditTerminal(int TerminalId)
		{
			var model = GetModel(TerminalId);
			return View("TerminalDetails", model);
		}

		[ValidateAntiForgeryToken]
		[HttpPost]
		[Authorize(Roles = "Admin")]
		public ActionResult EditTerminal(TerminalModel terminal)
		{
			if (!string.IsNullOrEmpty(terminal.TerminalName))
			{
				var oldTerminal = _terminalManager.GetTerminalById(terminal.TerminalId);
				if (!oldTerminal.TerminalName.Equals(terminal.TerminalName, StringComparison.InvariantCultureIgnoreCase))
				{
					var record = _terminalManager.GetAllTerminals()
						.FirstOrDefault(x =>
							string.Equals(x.TerminalName, terminal.TerminalName, StringComparison.InvariantCultureIgnoreCase));
					if (record != null)
						ModelState.AddModelError(nameof(terminal.TerminalName),
							$"We already have terminal '{terminal.TerminalName}' in DB");
				}
			}
			if (ModelState.IsValid)
			{
				_terminalManager.EditTerminal(terminal.TerminalId, terminal.TerminalName);
				return RedirectToAction("Index");
			}

			return View("TerminalDetails", terminal);
		}

		private TerminalModel GetModel(int terminalId)
		{
			var terminal = _terminalManager.GetTerminalById(terminalId);
			var model = new TerminalModel
			{
				TerminalId = terminal.TerminalId,
				TerminalName = terminal.TerminalName,

			};

			return model;
		}
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteTerminal(int terminalId)
        {
            try
            {

                var model = GetModel(terminalId);
                return View(model);
            }

            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteTerminal(TerminalModel terminal)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _terminalManager.DeleteTerminal(terminal.TerminalId);
                    return RedirectToAction("Index");
                }
                else
                {
                    return HttpNotFound();
                }

            }

            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }
    }
}

MVC2/Views/Terminal/DeleteTerminal.cshtml
@model MVC2.Models.Terminals.TerminalModel

@{
    ViewBag.Title = "Terminal Delete";
}


<h3>Are you sure you want to delete this terminal?</h3>

<div class="container body-content" style="margin-top: 20px;">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(x => x.TerminalName)

            <div class="form-group">
               
                    @Html.DisplayNameFor(model => model.TerminalName)
             
                    @Html.DisplayFor(model => model.TerminalName)
                    @Html.ValidationMessageFor(model => model.TerminalName, "", new { @class = "text-danger" })
               
                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </div>
            </div>


        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

MVC2/Views/Terminal/Index.cshtml
@model Airport.Core.Models.Terminal[]

@{
	ViewBag.Title = "Terminals";
	var RoleAdmin = ViewBag.RoleAdmin;
}
<section class="content">
	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">Terminal Table</h3>
				</div>
				<!-- /.box-header -->
				<div class="box-body">
					<table id="terminal" class="table table-bordered table-hover">
						<thead>
							<tr>
								<th>TerminalId</th>
								<th>TerminalName</th>
								@if (RoleAdmin)
								{
									<th>Actions</th>
								}
							</tr>
						</thead>
						<tbody>
							@foreach (var itm in Model)
							{
								<tr id="companyId-@itm.TerminalId">
									<td>@itm.TerminalId</td>
									<td>@itm.TerminalName</td>
									@if (RoleAdmin)
									{
                                    <td>
                                        @*<span>@Html.ActionLink("Edit", "EditCity", new { cityId = itm.CityId })</span>*@
                                        @Html.ActionLink("Edit", "EditTerminal", new { terminalId = itm.TerminalId }, new { @class = "btn btn-primary btn-success btn-xs" })
                                        @Html.ActionLink("Delete", "DeleteTerminal", new { terminalId = itm.TerminalId }, new { @class = "btn btn-primary btn-danger btn-xs" })
                                    </td>
									}
								</tr>
							}
						</tbody>
						<tfoot>
							<tr>
								<th>TerminalId</th>
								<th>TerminalName</th>
								@if (RoleAdmin)
								{
									<th>Actions</th>
								}
							</tr>
						</tfoot>
					</table>
				</div>
				<!-- /.box-body -->
			</div>
			@if (RoleAdmin)
			{
				@Html.ActionLink("Add new terminal", "AddNewTerminal", routeValues: null, htmlAttributes: new { id = "AddLink", @class = "btn bg-orange btn-flat margin" })
			}
		</div>
	</div>
</section>
@section Scripts{
	<script>
		$(function () {
			$('#terminal').DataTable({
				'paging': true,
				'lengthChange': false,
				'searching': false,
				'ordering': true,
				'info': true,
				'autoWidth': false
			})
		})
	</script>
}
@*@section Styles{
		<style type="text/css">
			table {
				width: 100%;
			}

			table, th, td {
				border: 1px solid black;
				padding: 10px;
			}

			table thead th {
				background-color: green;
				color: white;
			}

			table tbody tr.selected {
				background-color: pink;
			}
		</style>
	}

	<h2>Terminals</h2>
	<div class="container">
		<div class="row">
			<div class="col-md-7">
				<table>
					<thead>
					<tr>
						<th>TerminalId</th>
						<th>TerminalName</th>
						<th>Actions</th>
					</tr>
					</thead>
					<tbody>
					@foreach (var itm in Model)
					{
						<tr id="terminalId-@itm.TerminalId">
							<td>@itm.TerminalId</td>
							<td>@itm.TerminalName</td>
							<td>
								<span>@Html.ActionLink("Edit", "EditTerminal", new { terminalId = itm.TerminalId })</span>
							</td>
						</tr>
					}
					</tbody>
				</table>

				<div style="margin-top: 20px; margin-left: 10px; margin-bottom: 20px;">
					@Html.ActionLink("Add new terminal", "AddNewTerminal")
				</div>
			</div>

			@*<div class="col-md-5" id="cityDetails" style="border: solid 1px black; padding: 10px;">
				<h2>City details will be here</h2>
			</div>*@
@*</div>
	</div>*@

MVC2/Views/Terminal/TerminalDetails.cshtml
@model  MVC2.Models.Terminals.TerminalModel

@{
	var action = Model.TerminalId > 0 ? "EditTerminal" : "AddNewTerminal";
	var header = Model.TerminalId > 0 ? "Edit terminal" : "Add new terminal";
	var buttonText = Model.TerminalId > 0 ? "Save" : "Create";
}

<div class="container body-content" style="margin-top: 20px;">
    @using (Html.BeginForm(action, "Terminal", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>@header</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(x => x.TerminalId)

            <div class="form-group">
                @Html.LabelFor(model => model.TerminalName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TerminalName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TerminalName, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="@buttonText" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>