MVC2/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Airport.Core.Interfaces.Managers;
using MVC2.Models.Companies;

namespace MVC2.Controllers
{
	public class CitiesController : Controller
    {
	    public CitiesController()
	    {

	    }
	    private readonly ICityManager _cityManager;
	    //private readonly List<CityModel> _cities;

	    public CitiesController(ICityManager cityManager)
	    {
			_cityManager = cityManager;
		    
		}
		// GET: Cities
		public ActionResult Index()
		{
			ViewBag.RoleAdmin = User.IsInRole("Admin");
	        var cities = _cityManager.GetAllCities();
	        return View(cities);
        }
	    [Authorize(Roles = "Admin")]
		public ActionResult AddNewCity()
		{
			var model = new CityModel();

			return View("CityDetails", model);
		}

	    [ValidateAntiForgeryToken]
	    [HttpPost]
	    [Authorize(Roles = "Admin")]
		public ActionResult AddNewCity(CityModel city)
	    {
		    if (!string.IsNullOrEmpty(city.CityName))
		    {
			    var record = _cityManager.GetAllCities()
				    .FirstOrDefault(x => string.Equals(x.CityName, city.CityName, StringComparison.InvariantCultureIgnoreCase));
			    if (record != null) ModelState.AddModelError(nameof(city.CityName), $"We already have city '{city.CityName}' in DB");
		    }

		    if (ModelState.IsValid)
		    {
			    _cityManager.AddCity(city.CityName);
			    return RedirectToAction("Index");
		    }

		    return View("CityDetails", city);
	    }
	    [Authorize(Roles = "Admin")]
		public ActionResult EditCity(int CityId)
	    {
		    var model = GetModel(CityId);
		    return View("CityDetails", model);
	    }

		[ValidateAntiForgeryToken]
		[HttpPost]
		[Authorize(Roles = "Admin")]
		public ActionResult EditCity(CityModel city)
		{
			if (!string.IsNullOrEmpty(city.CityName))
			{
				var oldCity = _cityManager.GetCityById(city.CityId);
				if (!oldCity.CityName.Equals(city.CityName, StringComparison.InvariantCultureIgnoreCase))
				{
					var record = _cityManager.GetAllCities()
						.FirstOrDefault(x => string.Equals(x.CityName, city.CityName, StringComparison.InvariantCultureIgnoreCase));
					if (record != null)
						ModelState.AddModelError(nameof(city.CityName), $"We already have city '{city.CityName}' in DB");
				}
			}
			if (ModelState.IsValid)
			{
				_cityManager.EditCity(city.CityId, city.CityName);
				return RedirectToAction("Index");
			}

			return View("CityDetails", city);
		}

		private CityModel GetModel(int cityId)
	    {
		    var city = _cityManager.GetCityById(cityId);
		    var model = new CityModel
		    {
			    CityId = city.CityId,
			    CityName = city.CityName,
			   
		    };

		    return model;
	    }
        //[Authorize(Roles = "Admin")]
        //public ActionResult DeleteCity(int cityId)
        //{
        //    try
        //    {

        //        var model = GetModel(cityId);
        //        return View(model);
        //    }

        //    catch (Exception)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }

        //}

       
 
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteCity(int cityId)
        {

                    _cityManager.DeleteCity(cityId);
                    return RedirectToAction("Index");
       
        }
    }
}

MVC2/Views/Cities/AddNewCity.cshtml
@model MVC2.Models.Companies.CityModel

@{
    ViewBag.Title = "AddNewCity";
}

<h2>AddNewCity</h2>

MVC2/Views/Cities/CityDetails.cshtml
@model  MVC2.Models.Companies.CityModel

@{
	var action = Model.CityId > 0 ? "EditCity" : "AddNewCity";
	var header = Model.CityId > 0 ? "Edit city" : "Add new city";
	var buttonText = Model.CityId > 0 ? "Save" : "Create";
}

<div class="container body-content" style="margin-top: 20px;">
    @using (Html.BeginForm(action, "Cities", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>@header</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(x => x.CityId)

            <div class="form-group">
                @Html.LabelFor(model => model.CityName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="@buttonText" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

MVC2/Views/Cities/DeleteCity.cshtml
@model MVC2.Models.Companies.CityModel

@{
    ViewBag.Title = "City Delete";
}


<h3>Are you sure you want to delete this city?</h3>

<div class="container body-content" style="margin-top: 20px;">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(x => x.CityName)

            <div class="form-group">
                
                    @Html.DisplayNameFor(model => model.CityName)
               
                    @Html.DisplayFor(model => model.CityName)
                    @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
                
                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </div>
            </div>


        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

MVC2/Views/Cities/Index.cshtml
@model Airport.Core.Models.City[]

@{
	ViewBag.Title = "Cities";
	var RoleAdmin = ViewBag.RoleAdmin;
}


<section class="content">
	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">Cities Table</h3>
				</div>
				<!-- /.box-header -->
				<div class="box-body">
					<table id="example2" class="table table-bordered table-hover">
						<thead>
							<tr>
								<th>CityId</th>
								<th>CityName</th>
								@if (RoleAdmin)
								{
									<th>Actions</th>
								}
							</tr>
						</thead>
						<tbody>
							@foreach (var itm in Model)
							{
								<tr id="companyId-@itm.CityId">
									<td>@itm.CityId</td>
									<td>@itm.CityName</td>
									@if (RoleAdmin)
									{
                                    <td>
                                        @*<span>@Html.ActionLink("Edit", "EditCity", new { cityId = itm.CityId })</span>*@
                                        <span>@Html.ActionLink("Edit", "EditCity", new { cityId = itm.CityId }, new { @class = "btn btn-primary btn-success btn-xs" })</span>
                                        @Html.ActionLink("Delete", "DeleteCity", new { cityId = itm.CityId }, new { @class = "btn btn-primary btn-danger btn-xs" })
                                    </td>
									}
								</tr>
							}
						</tbody>
						<tfoot>
							<tr>
								<th>CityId</th>
								<th>CityName</th>
								@if (RoleAdmin)
								{
									<th>Actions</th>
								}
							</tr>
						</tfoot>
					</table>
				</div>
				<!-- /.box-body -->
				@if (RoleAdmin)
				{
					<div>
						@Html.ActionLink("Add new city", "AddNewCity", routeValues: null, htmlAttributes: new { id = "AddLink", @class = "btn bg-orange btn-flat margin" })
					</div>
				}
			</div>
		</div>
	</div>
</section>
@section Scripts{
	<script>
		$(function () {
			$('#example2').DataTable({
				'paging': true,
				'lengthChange': false,
				'searching': false,
				'ordering': true,
				'info': true,
				'autoWidth': false
			})
		})
	</script>
}
@*@section Styles{
		<style type="text/css">
			table {
				width: 100%;
			}

			table, th, td {
				border: 1px solid black;
				padding: 10px;
			}

			table thead th {
				background-color: green;
				color: white;
			}

			table tbody tr.selected {
				background-color: pink;
			}
		</style>
	}*@
@*<div class="col-md-5" id="cityDetails" style="border: solid 1px black; padding: 10px;">
				<h2>City details will be here</h2>
			</div>
		</div>
	</div>
	@*<h2>Cities</h2>
	<div class="container">
		<div class="row">
			<div class="col-md-7">
				<table>
					<thead>
						<tr>
							<th>CityId</th>
							<th>CityName</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						@foreach (var itm in Model)
						{
							<tr id="companyId-@itm.CityId">
								<td>@itm.CityId</td>
								<td>@itm.CityName</td>
								<td>
									<span>@Html.ActionLink("Edit", "EditCity", new { cityId = itm.CityId })</span>
								</td>
							</tr>
						}
					</tbody>
				</table>

				<div style="margin-top: 20px; margin-left: 10px; margin-bottom: 20px;">
					@Html.ActionLink("Add new city", "AddNewCity")
				</div>
			</div>

			@*<div class="col-md-5" id="cityDetails" style="border: solid 1px black; padding: 10px;">
				<h2>City details will be here</h2>
			</div>
		</div>
	</div>*@