MVC2/Models/Flights/FlightModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Airport.Core.Enums;
using Airport.Core.Models;
using MVC2.Models.Companies;

namespace MVC2.Models.Flights
{
    public class FlightModel
    {
		public int FlightId { get; set; }

	    [DisplayName("Flight number")]
		public string FlightNumber { get; set; }

	    [DisplayName("Flight date time")]
        [DisplayFormat(DataFormatString = "{0:s}", ApplyFormatInEditMode = true)]
        public DateTime FlightDateTime { get; set; }

	    [DisplayName("Flight duration")]
	    [DisplayFormat(DataFormatString = "{0:hh\\:mm}", ApplyFormatInEditMode = true)]
		public TimeSpan FlightDuration { get; set; }

	    public FlightStatusEnum FlightStatusId { get; set; }

	    //[DisplayName("City from")]
		public int CityFromId { get; set; }

	    //[DisplayName("City to")]
		public int CityToId { get; set; }

	    public int CompanyId { get; set; }

	    public int TerminalId { get; set; }

	    public int SelectedCityFromId { get; set; }

	    public int SelectedCityToId { get; set; }

	    public int SelectedCompanyId { get; set; }

	    public int SelectedTerminalId { get; set; }

		[DisplayName("City")]
		public List<City> Cities { get; set; }

		[DisplayName("Company")]
		public List<Company> Companies { get; set; }

	    [DisplayName("Terminal")]
		public List<Terminal> Terminals { get; set; }
	}
}

MVC2/Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Airport.Core.Enums;
using Airport.Core.Interfaces.Managers;
using Airport.Core.Interfaces.Repositories;
using Airport.Core.Models;
using MVC2.Models.Flights;

namespace MVC2.Controllers
{
	public class FlightsController : Controller
	{
		private readonly IFlightManager _flightManager;
		private readonly ICompanyRepository _companyRepository;
		private readonly ICityRepository _cityRepository;
		private readonly ITerminalRepository _terminalRepository;
		private readonly List<City> _cities;
		private readonly List<Company> _companies;
		private readonly List<Terminal> _terminals;

		public FlightsController() : base()
		{


		}
		public FlightsController(IFlightManager flightManager,
								 ICompanyRepository companyRepository,
								 ICityRepository cityRepository,
								 ITerminalRepository terminalRepository)
		{
			_flightManager = flightManager;
			_companyRepository = companyRepository;
			_cityRepository = cityRepository;
			_terminalRepository = terminalRepository;
			_companies = companyRepository.SelectAll().OrderBy(x => x.CompanyName).ToList();
			_cities = cityRepository.SelectAll().OrderBy(x => x.CityName).ToList();
			_terminals = terminalRepository.SelectAll().OrderBy(x => x.TerminalName).ToList();
		}
		// GET: Flights
		public ActionResult Index()
		{
			ViewBag.RoleAdmin = User.IsInRole("Admin");
			var flights = _flightManager.GetAllFlights();
			return View(flights);
		}
		[Authorize(Roles = "Admin")]
		public ActionResult AddNewFlight()
		{
			var model = new FlightModel
			{
				Cities = _cities,
				Companies = _companies,
				Terminals = _terminals
			};

			return View("FlightDetails", model);
		}

		[ValidateAntiForgeryToken]
		[HttpPost]
		[Authorize(Roles = "Admin")]
		public ActionResult AddNewFlight(FlightModel flight)
		{
			if (!string.IsNullOrEmpty(flight.FlightNumber))
			{
				var record = _flightManager.GetAllFlights()
					.FirstOrDefault(x => string.Equals(x.FlightNumber, flight.FlightNumber, StringComparison.InvariantCultureIgnoreCase));
				if (record != null) ModelState.AddModelError(nameof(flight.FlightNumber), $"We already have flight '{flight.FlightNumber}' in DB");
                if (flight.SelectedCityToId == flight.SelectedCityFromId) ModelState.AddModelError(nameof(flight.SelectedCityToId), $"You cannot select the same city for departure and arrival");
            }

			if (ModelState.IsValid)
			{
				_flightManager.AddFlight(flight.FlightNumber, flight.FlightDateTime, flight.FlightDuration, (int)flight.FlightStatusId,
										 flight.SelectedCityFromId, flight.SelectedCityToId, flight.SelectedCompanyId, flight.SelectedTerminalId);
				return RedirectToAction("Index");
			}
			flight.Terminals = _terminals;
			flight.Cities = _cities;
			flight.Companies = _companies;
			return View("FlightDetails", flight);
		}

		[Authorize(Roles = "Admin")]
		public ActionResult EditFlight(int flightId)
		{
			var model = GetModel(flightId);
			return View("FlightDetails", model);
		}

		[ValidateAntiForgeryToken]
		[HttpPost]
		[Authorize(Roles = "Admin")]
		public ActionResult EditFlight(FlightModel flight)
		{
           
            if (flight.SelectedCityToId == flight.SelectedCityFromId) ModelState.AddModelError(nameof(flight.SelectedCityToId), $"You cannot select the same city for departure and arrival");
            if (ModelState.IsValid)
			{
				_flightManager.EditFlight(flight.FlightId, flight.FlightNumber, flight.FlightDateTime, flight.FlightDuration, (int)flight.FlightStatusId,
					flight.SelectedCityFromId, flight.SelectedCityToId, flight.SelectedCompanyId, flight.SelectedTerminalId);
				return RedirectToAction("Index");
			}
			flight.Terminals = _terminals;
			flight.Cities = _cities;
			flight.Companies = _companies;
			return View("FlightDetails", flight);
		}
		private FlightModel GetModel(int flightId)
		{
			var flight = _flightManager.GetFlightById(flightId);
			var model = new FlightModel
			{
				FlightId = flight.FlightId,
				FlightNumber = flight.FlightNumber,
				FlightDateTime = flight.FlightDateTime,
				FlightDuration = flight.FlightDuration,
				Cities = _cities,
				SelectedCityFromId = flight.CityFromId,
				SelectedCityToId = flight.CityToId,
				Companies = _companies,
				SelectedCompanyId = flight.CompanyId,
				Terminals = _terminals,
				SelectedTerminalId = flight.TerminalId,
				FlightStatusId = (FlightStatusEnum)flight.FlightStatusId
			};

			return model;
		}
		[Authorize(Roles = "Admin")]
		public ActionResult DeleteFlight(int flightId)
		{
			try
			{

				var model = GetModel(flightId);
				return View(model);
			}

			catch (Exception)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

		}

		[ValidateAntiForgeryToken]
		[HttpPost]
		[Authorize(Roles = "Admin")]
		public ActionResult DeleteFlight(FlightModel flight)
		{
			try
			{
				if (ModelState.IsValid)
				{
					_flightManager.DeleteFlight(flight.FlightId);
					return RedirectToAction("Index");
				}
				else
				{
					return HttpNotFound();
				}
				//flight.Terminals = _terminals;
				//flight.Cities = _cities;
				//flight.Companies = _companies;
				//return View("FlightDetails", flight);
			}

			catch (Exception)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
		}
	}
}

MVC2/Views/Flights/DeleteFlight.cshtml
@model MVC2.Models.Flights.FlightModel

@{
	ViewBag.Title = "Flight Delete";
}


<h3>Are you sure you want to delete this flight?</h3>

<div class="container body-content" style="margin-top: 20px;">
	@using (Html.BeginForm())
	{
		@Html.AntiForgeryToken()

		<div class="form-horizontal">
			@Html.ValidationSummary(true, "", new { @class = "text-danger" })

			@Html.HiddenFor(x => x.CompanyId)

			<div class="form-group">
				
					@Html.DisplayNameFor(model => model.FlightNumber)
				
					@Html.DisplayFor(model => model.FlightNumber)
					@Html.ValidationMessageFor(model => model.FlightNumber, "", new { @class = "text-danger" })
				
				<div class="form-actions no-color">
					<input type="submit" value="Delete" class="btn btn-danger" />
				</div>
				</div>


			</div>
	}

	<div>
		@Html.ActionLink("Back to List", "Index")
	</div>
</div>

MVC2/Views/Flights/FlightDetails.cshtml
@using System.Collections
@using Airport.Core.Enums
@model MVC2.Models.Flights.FlightModel

@{
	var action = Model.FlightId > 0 ? "EditFlight" : "AddNewFlight";
	var header = Model.FlightId > 0 ? "Edit flight" : "Add new flight";
	var buttonText = Model.FlightId > 0 ? "Save" : "Create";
}

<div class="container body-content" style="margin-top: 20px;">
	@using (Html.BeginForm(action, "Flights", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
	{
		@Html.AntiForgeryToken()

		<div class="form-horizontal">
			<h4>@header</h4>
			<hr />
			@Html.ValidationSummary(true, "", new { @class = "text-danger" })

			@Html.HiddenFor(x => x.FlightId)

			<div class="form-group">
				@Html.LabelFor(model => model.FlightNumber, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.FlightNumber, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.FlightNumber, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.FlightDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.FlightDateTime, new { htmlAttributes = new { @class = "form-control", type = "datetime-local",
                   @Value = Model.FlightDateTime.ToString() == DateTime.MinValue.ToString() ?  DateTime.Now.ToString("s") : Model.FlightDateTime.ToString("s") } })
					@Html.ValidationMessageFor(model => model.FlightDateTime, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.FlightDuration, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.FlightDuration, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.FlightDuration, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.FlightStatusId, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					<select name="FlightStatusId" id="FlightStatusId" class="form-control" placeholder="Select status">
						@foreach (var itm in Enum.GetValues(typeof(FlightStatusEnum)))
						{
							if (Model.FlightStatusId == (FlightStatusEnum)itm)
							{
								<option name="FlightStatus" value="@itm" selected>@Enum.GetName(typeof(FlightStatusEnum), itm).Replace("_", " ")</option>
							}
							else
							{
								<option name="FlightStatus" value="@itm">@Enum.GetName(typeof(FlightStatusEnum), itm).Replace("_", " ")</option>
							}
						}
					</select>
				</div>
			</div>
            <div class="form-group">
                @Html.LabelFor(model => model.Cities, "Departure city", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.ValidationMessageFor(model => model.SelectedCityToId, "", new { @class = "text-danger" })
                <div class="col-md-10">
                    <select name="SelectedCityFromId" id="CityFromId" class="form-control" placeholder="Select city">
                        @foreach (var itm in Model.Cities)
                        {
                            if (Model.SelectedCityFromId == itm.CityId)
                            {
                                <option name="City" value="@itm.CityId" selected>@itm.CityName</option>
                            }
                            else
                            {
                                <option name="City" value="@itm.CityId">@itm.CityName</option>
                            }
                        }
                    </select>
                </div>
            </div>

			<div class="form-group">
				@Html.LabelFor(model => model.Cities, "City of arrival", htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					<select name="SelectedCityToId" id="CityToId" class="form-control" placeholder="Select city">
						@foreach (var itm in Model.Cities)
						{
							if (Model.SelectedCityToId == itm.CityId)
							{
								<option name="City" value="@itm.CityId" selected>@itm.CityName</option>
							}
							else
							{
								<option name="City" value="@itm.CityId">@itm.CityName</option>
							}
						}
					</select>
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.Companies, "Company", htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					<select name="SelectedCompanyId" id="CompanyId" class="form-control" placeholder="Select company">
						@foreach (var itm in Model.Companies)
						{
							if (Model.SelectedCompanyId == itm.CompanyId)
							{
								<option name="Company" value="@itm.CompanyId" selected>@itm.CompanyName</option>
							}
							else
							{
								<option name="Company" value="@itm.CompanyId">@itm.CompanyName</option>
							}
						}
					</select>
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.Terminals, "Terminal", htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					<select name="SelectedTerminalId" id="TerminalId" class="form-control" placeholder="Select terminal">
						@foreach (var itm in Model.Terminals)
						{
							if (Model.SelectedTerminalId == itm.TerminalId)
							{
								<option name="City" value="@itm.TerminalId" selected>@itm.TerminalName</option>
							}
							else
							{
								<option name="City" value="@itm.TerminalId">@itm.TerminalName</option>
							}
						}
					</select>
				</div>
			</div>
			@*<div class="form-group">
					@Html.DropDownListFor(model => model.CityToId, new SelectList(Model.Cities, "CityId", "CityName", Model.CityToId), "Please select city", new { @class = "form-control" })
				</div>*@
			@*<div class="form-group">
					@Html.LabelFor(model => model.CityFromId, htmlAttributes: new { @class = "control-label col-md-2" })
					<div class="col-md-10">
						@Html.DropDownListFor(model => model.CityFromId, new SelectList(Model.Cities.Select(x => x.CityName)), "Please select city", new { @class = "form-control" })
					</div>
				</div>

				<div class="form-group">
					@Html.LabelFor(model => model.CityToId, htmlAttributes: new { @class = "control-label col-md-2" })
					<div class="col-md-10">
						@Html.DropDownListFor(model => model.CityToId, new SelectList(Model.Cities.Select(x => x.CityName), "CityId", "CityName"), "Please select city", new { @class = "form-control" })
					</div>
				</div>*@

			@*<div class="form-group">
					@Html.LabelFor(model => model.Companies, htmlAttributes: new { @class = "control-label col-md-2" })
					<div class="col-md-10">
						@Html.DropDownList("Companies", new SelectList(Model.Companies.Select(x => x.CompanyName)), "Please select company", new { @class = "form-control" })
					</div>
				</div>

				<div class="form-group">
					@Html.LabelFor(model => model.Terminals, htmlAttributes: new { @class = "control-label col-md-2" })
					<div class="col-md-10">
						@Html.DropDownList("Terminals", new SelectList(Model.Terminals.Select(x => x.TerminalName)), "Please select terminal", new { @class = "form-control" })
					</div>
				</div>*@

			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<input type="submit" value="@buttonText" class="btn btn-primary" />
				</div>
			</div>



			<div>
				@Html.ActionLink("Back to List", "Index")
			</div>
		</div>
	}
</div>

MVC2/Views/Flights/Index.cshtml
@using Airport.Core.Enums
@model Airport.Core.Models.Flight[]

@{
	ViewBag.Title = "Flights";
	var RoleAdmin = ViewBag.RoleAdmin;
}

<section class="content">
	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">Flights Table</h3>
				</div>
				<!-- /.box-header -->
				<div class="box-body">
					<table id="flights" class="table table-bordered table-hover">
						<thead>
							<tr>
								<th>FlightId</th>
								<th>FlightNumber</th>
								<th>FlightDateTime</th>
								<th>ArrivalDateTime</th>
								<th>FlightStatus</th>
								<th>CityFromId</th>
								<th>CityToId</th>
								<th>CompanyId</th>
								<th>TerminalId</th>
								@if (RoleAdmin)
								{
									<th>Actions</th>
								}
							</tr>
						</thead>
						<tbody>
							@foreach (var itm in Model)
							{
								<tr id="flightId-@itm.FlightId">
									<td>@itm.FlightId</td>
									<td>@itm.FlightNumber</td>
									<td>@itm.FlightDateTime</td>
									<td>@itm.FlightDateTime.Add(itm.FlightDuration)</td>
									<td>
										@{ var flightStatus = ((FlightStatusEnum)itm.FlightStatusId).ToString().Replace('_', ' '); }
										@flightStatus
									</td>
									<td>@itm.CityFrom.CityName</td>
									<td>@itm.CityTo.CityName</td>
									<td>@itm.Company.CompanyName</td>
									<td>@itm.Terminal.TerminalName</td>
									@if (RoleAdmin)
									{
										<td>
											@*<span>@Html.ActionLink("Edit", "EditFlight", new { flightId = itm.FlightId })</span>*@
											@Html.ActionLink("Edit", "EditFlight", new { flightId = itm.FlightId }, new { @class = "btn btn-primary btn-success btn-xs" })
											@Html.ActionLink("Delete", "DeleteFlight", new { flightId = itm.FlightId }, new { @class = "btn btn-primary btn-danger btn-xs" })
										</td>
									}
								</tr>
							}
						</tbody>
						<tfoot>
							<tr>
								<th>FlightId</th>
								<th>FlightNumber</th>
								<th>FlightDateTime</th>
								<th>ArrivalDateTime</th>
								<th>FlightStatus</th>
								<th>CityFromId</th>
								<th>CityToId</th>
								<th>CompanyId</th>
								<th>TerminalId</th>
								@if (RoleAdmin)
								{
									<th>Actions</th>
								}
							</tr>
						</tfoot>
					</table>
				</div>
				<!-- /.box-body -->
			</div>
			@if (RoleAdmin)
			{
				@Html.ActionLink("Add new flight", "AddNewFlight", routeValues: null, htmlAttributes: new { id = "AddLink", @class = "btn bg-orange btn-flat margin" })
			}
		</div>
	</div>
</section>
@section Scripts{
	<script>
		$(function () {
			$('#flights').DataTable({
				'paging': true,
				'lengthChange': false,
				'searching': false,
				'ordering': true,
				'info': true,
				'autoWidth': false
			})
		})
	</script>
}

@*@section Styles{
		<style type="text/css">
			table {
				width: 100%;
			}

			table, th, td {
				border: 1px solid black;
				padding: 10px;
			}

				table thead th {
					background-color: green;
					color: white;
				}

				table tbody tr.selected {
					background-color: pink;
				}
		</style>
	}*@

@*<h2>Flights</h2>
	<div class="container">
		<div class="row">
			<div class="col-md-7">
				<table>
					<thead>
						<tr>
							<th>FlightId</th>
							<th>FlightNumber</th>
							<th>FlightDateTime</th>
							<th>ArrivalDateTime</th>
							<th>FlightStatus</th>
							<th>CityFromId</th>
							<th>CityToId</th>
							<th>CompanyId</th>
							<th>TerminalId</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						@foreach (var itm in Model)
						{
						<tr id="flightId-@itm.FlightId">
							<td>@itm.FlightId</td>
							<td>@itm.FlightNumber</td>
							<td>@itm.FlightDateTime</td>
							<td>@itm.FlightDateTime.Add(itm.FlightDuration)</td>
							<td>
								@{ var flightStatus = ((FlightStatusEnum) itm.FlightStatusId).ToString().Replace('_', ' '); }
								@flightStatus
							</td>
							<td>@itm.CityFrom.CityName</td>
							<td>@itm.CityTo.CityName</td>
							<td>@itm.Company.CompanyName</td>
							<td>@itm.Terminal.TerminalName</td>
							<td>
								<span>@Html.ActionLink("Edit", "EditFlight", new { flightId = itm.FlightId })</span>
							</td>
						</tr>
						}
					</tbody>
				</table>

				<div style="margin-top: 20px; margin-left: 10px; margin-bottom: 20px;">
					@Html.ActionLink("Add new flight", "AddNewFlight")
				</div>
			</div>

			@*<div class="col-md-5" id="cityDetails" style="border: solid 1px black; padding: 10px;">
					<h2>City details will be here</h2>
				</div>
		</div>
	</div>*@